#!/bin/sh


export SCRIPT_DIR=$(dirname "`realpath ${0}`")
export SOURCES_DIR="${SCRIPT_DIR}"/sources
export BUILD_SCRIPTS="${SCRIPT_DIR}"/build_scripts
export BUILD_DIR="${SCRIPT_DIR}"/build
export ARCH=$(uname -m)

source "${SCRIPT_DIR}/custom_vars"

export LFS=${LFS:-${SCRIPT_DIR}/system}

if [ ! -d "${LFS}/${TOOLS}" ]
then
    mkdir -pv "${LFS}/${TOOLS}"
    chown -v ${USER} "${LFS}/${TOOLS}"
fi

sudo rm "/${TOOLS}"
sudo ln -sv "${LFS}/${TOOLS}" /

for script in "${BUILD_SCRIPTS}/tools"/???-*
do
    script_name=`basename "${script}"`
    doingmsg "###### Running: ${script_name} ######"
    sh "${script}"
    result=$?
    case "${result}" in
        0)
            continue
        ;;
        *)
            errmsg "###### ${script_name}: Error ${result} ######"
            exit "${result}"
        ;;
    esac
    donemsg "###### ${script_name}: OK ######"
done

{
    doingmsg "###### Finishing: ######"
    strip --strip-debug "/${TOOLS}"/lib/*
    /usr/bin/strip --strip-unneeded "/${TOOLS}"/{,s}bin/*
    rm -rf "/${TOOLS}"/{,share}/{info,man,doc}
    find "/${TOOLS}"/{lib,libexec} -name \*.la -delete
    sudo chown -R root:root "${LFS}/${TOOLS}"
    sudo rm "/${TOOLS}"
    donemsg "###### Finishing: OK ######"
} || {
    errmsg "###### Finishing: Error ######"
    exit
}