#!/bin/sh


SCRIPT_DIR=$(dirname "`realpath ${0}`")

SOURCES_DIR="${SCRIPT_DIR}"/sources
BUILD_SCRIPTS="${SCRIPT_DIR}"/build_scripts
BUILD_DIR="${SCRIPT_DIR}"/build

ARCH=$(uname -m)

source "${SCRIPT_DIR}/custom_vars"

if [ ! -d  "${LFS}" ]
then
    LFS="${SCRIPT_DIR}"/system
fi

if [ ! -d "${LFS}/${CUSTOM_PREFIX}" ]
then
    mkdir -pv "${LFS}/${CUSTOM_PREFIX}"
    chown -v ${USER} "${LFS}/${CUSTOM_PREFIX}"
fi

sudo rm "/${CUSTOM_PREFIX}"
sudo ln -sv "${LFS}/${CUSTOM_PREFIX}" /

export LFS LC_ALL LFS_TGT PATH MAKEFLAGS SOURCES_DIR BUILD_DIR ARCH BUILD_SCRIPTS CUSTOM_PREFIX

for script in "${BUILD_SCRIPTS}/tools"/???-*
do
    sh "${script}"
    result=$?
    case "${result}" in
        1)
            exit "${result}"
        ;;
        2)
            exit "${result}"
        ;;
    esac
done




