#!/bin/sh

tool_builddir="${BUILD_DIR}/${tool_name}.pkg"
tool_sourcefile=`ls "${SOURCES_DIR}/${tool_name}"*tar.*z*`

function cleanup(){
    rm -rf "${tool_builddir}"
}

function extract(){
    mkdir -pv "${2}"
    tar --strip-components=1 -C "${2}" -xf "${1}"
}

function patchsrc(){
    patch -Np1 -i "${1}"
}

if [ ! -d "${tool_builddir}" ]
then
    if [ -f "${tool_sourcefile}" ]
    then
        extract "${tool_sourcefile}" "${tool_builddir}"
    else
        printf "Error: '${tool_sourcefile}' file not found\n"
        cleanup
        exit 1
    fi
else
    if [ "${exit_on_builddir_exists}" == "true" ]
    then
        exit 0
    fi
fi

cd "${tool_builddir}"

