#!/bin/sh

scripts_dir="${BUILD_SCRIPTS}/tools"
tool_name=binutils
exit_on_builddir_exists=true

source "${scripts_dir}/functions"

{
    mkdir -v build-step1 &&
    cd build-step1 &&
    ../configure \
        --prefix="/${TOOLS}" \
        --with-sysroot=$LFS \
        --with-lib-path="/${TOOLS}/lib" \
        --target=$LFS_TGT \
        --disable-nls \
        --disable-werror &&
    make &&
    {
        case "${ARCH}" in
            x86_64)
                mkdir -v "/${TOOLS}/lib" && ln -sv lib "/${TOOLS}/lib64"
            ;;
        esac
        make install
    }
} || {
    cleanup
    exit 2
}

