#!/bin/sh

scripts_dir="${BUILD_SCRIPTS}/tools"
tool_name=gcc
exit_on_builddir_exists=true

source "${scripts_dir}/functions"

{
    extract `ls "${SOURCES_DIR}/mpfr"*tar.*z` mpfr &&
    extract `ls "${SOURCES_DIR}/gmp"*tar.*z` gmp &&
    extract `ls "${SOURCES_DIR}/mpc"*tar.*z` mpc &&
    {
        for file in gcc/config/{linux,i386/linux{,64}}.h
        do
            cp -uv $file{,.orig}
            sed -e "s@/lib\(64\)\?\(32\)\?/ld@/${TOOLS}&@g" \
                -e "s@/${CUSTOM_PREFIX}@/${TOOLS}@g" $file.orig > $file
            echo "
#undef STANDARD_STARTFILE_PREFIX_1
#undef STANDARD_STARTFILE_PREFIX_2
#define STANDARD_STARTFILE_PREFIX_1 \"/${TOOLS}/lib/\"
#define STANDARD_STARTFILE_PREFIX_2 \"\"" >> $file
            touch $file.orig
        done
        case "${ARCH}" in
            x86_64)
                sed -e '/m64=/s/lib64/lib/' \
                    -i.orig gcc/config/i386/t-linux64
            ;;
        esac
    } &&
    mkdir -v build &&
    cd build &&
    ../configure                                       \
        --target=$LFS_TGT                              \
        --prefix="/${TOOLS}"                   \
        --with-glibc-version=2.11                      \
        --with-sysroot=$LFS                            \
        --with-newlib                                  \
        --without-headers                              \
        --with-local-prefix="/${TOOLS}"        \
        --with-native-system-header-dir="/${TOOLS}/include" \
        --disable-nls                                  \
        --disable-shared                               \
        --disable-multilib                             \
        --disable-decimal-float                        \
        --disable-threads                              \
        --disable-libatomic                            \
        --disable-libgomp                              \
        --disable-libquadmath                          \
        --disable-libssp                               \
        --disable-libvtv                               \
        --disable-libstdcxx                            \
        --enable-languages=c,c++ &&
    make &&
    make install
} || {
    cleanup
    exit 2
}




