#!/bin/sh

scripts_dir="${BUILD_SCRIPTS}/tools"
tool_name=linux
exit_on_builddir_exists=true

source "${scripts_dir}/functions"

{
    make mrproper &&
    make headers &&
    cp -rv usr/include/* "/${TOOLS}/include"
} || {
    cleanup
    exit 2
}


