#!/bin/sh

scripts_dir="${BUILD_SCRIPTS}/tools"
tool_name=glibc
exit_on_builddir_exists=true

source "${scripts_dir}/functions"

{
    mkdir -v build &&
    cd build &&
    ../configure \
        --prefix="/${TOOLS}" \
        --host=$LFS_TGT \
        --build=$(../scripts/config.guess) \
        --enable-kernel=3.2 \
        --with-headers="/${TOOLS}/include" &&
    make &&
    make install
} || {
    cleanup
    exit 2
}
