#!/bin/sh

scripts_dir="${BUILD_SCRIPTS}/${TOOLS_BUILD_SCRIPTS_DIRNAME}"
tool_name=m4
exit_on_builddir_exists=true

source "${scripts_dir}/functions"

{
    sed -i 's/IO_ftrylockfile/IO_EOF_SEEN/' lib/*.c &&
    echo "#define _IO_IN_BACKUP 0x100" >> lib/stdio-impl.h &&
    mkdir -v build &&
    cd build &&
    ../configure --prefix="/${TOOLS}" &&
    make &&
    make install
} || {
    cleanup
    exit 2
}
