#!/bin/sh

scripts_dir="${BUILD_SCRIPTS}/${TOOLS_BUILD_SCRIPTS_DIRNAME}"
tool_name=bash
exit_on_builddir_exists=true

source "${scripts_dir}/functions"

{
    sed -i s/mawk// configure &&
    mkdir -v build &&
    cd build &&
    ../configure --prefix="/${TOOLS}" --without-bash-malloc &&
    make &&
    {
        make install &&
        ln -sv bash "/${TOOLS}/bin/sh"
    }
} || {
    cleanup
    exit 2
}