#!/bin/sh

scripts_dir="${BUILD_SCRIPTS}/${TOOLS_BUILD_SCRIPTS_DIRNAME}"
tool_name=coreutils
exit_on_builddir_exists=true

source "${scripts_dir}/functions"

{
    mkdir -v build &&
    cd build &&
    ../configure --prefix="/${TOOLS}" --enable-install-program=hostname &&
    make &&
    make install
} || {
    cleanup
    exit 2
}