#!/bin/sh

scripts_dir="${BUILD_SCRIPTS}/${TOOLS_BUILD_SCRIPTS_DIRNAME}"
tool_name=perl
exit_on_builddir_exists=true

source "${scripts_dir}/functions"

{
    sh Configure -des -Dprefix="/${TOOLS}" -Dlibs=-lm -Uloclibpth -Ulocincpth &&
    make &&
    {
        cp -v perl cpan/podlators/scripts/pod2man "/${TOOLS}/bin" &&
        mkdir -pv "/${TOOLS}/lib/perl5/5.30.1" &&
        cp -Rv lib/* "/${TOOLS}/lib/perl5/5.30.1"
    }
} || {
    cleanup
    exit 2
}