#!/bin/sh

scripts_dir="${BUILD_SCRIPTS}/${TOOLS_BUILD_SCRIPTS_DIRNAME}"
tool_name=Python
exit_on_builddir_exists=true

source "${scripts_dir}/functions"

{
    sed -i '/def add_multiarch_paths/a \        return' setup.py &&
    mkdir -v build &&
    cd build &&
    ../configure --prefix="/${TOOLS}" --without-ensurepip &&
    make &&
    make install
} || {
    cleanup
    exit 2
}