#!/bin/sh

scripts_dir="${BUILD_SCRIPTS}/${TOOLS_BUILD_SCRIPTS_DIRNAME}"
tool_name=util-linux
exit_on_builddir_exists=true

source "${scripts_dir}/functions"

{
    mkdir -v build &&
    cd build &&
    ../configure --prefix="/${TOOLS}" --without-python \
        --disable-makeinstall-chown \
        --without-systemdsystemunitdir \
        --without-ncurses \
        PKG_CONFIG="" &&
    make &&
    make install
} || {
    cleanup
    exit 2
}